#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import hashlib
import json
from pathlib import Path
from typing import List

import faiss
import pandas as pd

from src.embeddings import load_embedder

INDEX_MANIFEST_VERSION = 2
REQUIRED_INDEX_FILES = ["faiss.index", "meta.parquet", "manifest.json"]


def read_jsonl(path: Path) -> List[dict]:
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def sha256_file(path: Path) -> str:
    hasher = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            hasher.update(chunk)
    return hasher.hexdigest()


def manifest_path_info(path: Path | None) -> dict | None:
    if path is None:
        return None
    return {
        "path": path.as_posix(),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--chunks", required=True, help="chunks.jsonl generated by ingest.py")
    ap.add_argument("--out", required=True, help="Output folder for FAISS index + metadata")
    ap.add_argument("--model", default="local-hash-v1", help="Embedding model or local fallback backend")
    ap.add_argument("--ingest_manifest", default="", help="Optional ingest_manifest.json to bind into the index manifest")
    args = ap.parse_args()

    chunks_path = Path(args.chunks)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    rows = read_jsonl(chunks_path)
    if not rows:
        raise SystemExit("No chunks found.")

    texts = [r["text"] for r in rows]

    embedder = load_embedder(args.model)
    print(
        f"Embedding {len(texts)} chunks with model: {embedder.info.effective_model} "
        f"(backend={embedder.info.backend}, requested={args.model})"
    )

    embs = embedder.encode(
        texts,
        batch_size=32,
        show_progress_bar=True,
        normalize_embeddings=True,
    )

    d = embs.shape[1]
    index = faiss.IndexFlatIP(d)  # cosine similarity (via normalized vectors)
    index.add(embs)

    faiss.write_index(index, str(out_dir / "faiss.index"))

    meta = pd.DataFrame(rows)
    meta.insert(0, "faiss_id", range(len(meta)))
    for col in ["page_start", "page_end", "doc_total_pages", "chunk_schema_version"]:
        if col in meta.columns:
            meta[col] = meta[col].fillna(0).astype(int)
    meta.to_parquet(out_dir / "meta.parquet", index=False)

    ingest_manifest_path = Path(args.ingest_manifest) if args.ingest_manifest else chunks_path.with_name("ingest_manifest.json")
    manifest = {
        "index_manifest_version": INDEX_MANIFEST_VERSION,
        "requested_model": embedder.info.requested_model,
        "effective_model": embedder.info.effective_model,
        "backend": embedder.info.backend,
        "embedding_dim": d,
        "num_chunks": len(rows),
        "source_chunks": manifest_path_info(chunks_path),
        "source_chunks_sha256": sha256_file(chunks_path),
        "chunk_schema_version": rows[0].get("chunk_schema_version", 1),
        "metadata_columns": meta.columns.tolist(),
        "required_index_files": REQUIRED_INDEX_FILES,
        "source_ingest_manifest": manifest_path_info(ingest_manifest_path) if ingest_manifest_path.exists() else None,
        "source_ingest_manifest_sha256": sha256_file(ingest_manifest_path) if ingest_manifest_path.exists() else None,
    }
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    print(f"✅ Saved FAISS index to: {out_dir/'faiss.index'}")
    print(f"✅ Saved metadata to:   {out_dir/'meta.parquet'}")
    print(f"✅ Saved manifest to:   {out_dir/'manifest.json'}")


if __name__ == "__main__":
    main()
