#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import json
from pathlib import Path
from typing import List

import faiss
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer
from tqdm import tqdm


def read_jsonl(path: Path) -> List[dict]:
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--chunks", required=True, help="chunks.jsonl generated by ingest.py")
    ap.add_argument("--out", required=True, help="Output folder for FAISS index + metadata")
    ap.add_argument("--model", default="BAAI/bge-small-en-v1.5", help="SentenceTransformer embedding model")
    args = ap.parse_args()

    chunks_path = Path(args.chunks)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    rows = read_jsonl(chunks_path)
    if not rows:
        raise SystemExit("No chunks found.")

    texts = [r["text"] for r in rows]

    print(f"Embedding {len(texts)} chunks with model: {args.model}")
    model = SentenceTransformer(args.model)

    # encode in batches
    embs = model.encode(
        texts,
        batch_size=32,
        show_progress_bar=True,
        normalize_embeddings=True,
    ).astype("float32")

    d = embs.shape[1]
    index = faiss.IndexFlatIP(d)  # cosine similarity (via normalized vectors)
    index.add(embs)

    faiss.write_index(index, str(out_dir / "faiss.index"))

    meta = pd.DataFrame(
        [
            {
                "faiss_id": i,
                "doc_id": r["doc_id"],
                "chunk_id": r["chunk_id"],
                "section": r.get("section", ""),
                "page_start": int(r.get("page_start", 1)),
                "page_end": int(r.get("page_end", 1)),
                "text": r["text"],
            }
            for i, r in enumerate(rows)
        ]
    )
    meta.to_parquet(out_dir / "meta.parquet", index=False)

    print(f"✅ Saved FAISS index to: {out_dir/'faiss.index'}")
    print(f"✅ Saved metadata to:   {out_dir/'meta.parquet'}")


if __name__ == "__main__":
    main()
